name: Build TCPLS and run make check
on: [push]

jobs:
  build:
    name: Build and check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get install faketime libscope-guard-perl libtest-tcp-perl

      - name: CMake
        run: cmake .

      - name: Make
        run: make

      - name: Make check
        run: make check